#pragma once

#include "intl/intl_en.h"
#include "intl/intl_pl.h"

void loadtranslation(int SELECTED_LANGUAGE) {
	if (SELECTED_LANGUAGE == 1) { //english translataion
		Serial.println("English Translation!\n");
		TEXT_LANG = EN_INTL_LANG;

		TEXT_INDEX_PAGE = EN_INTL_INDEX_PAGE;
		TEXT_CONFIG_PAGE = EN_INTL_CONFIG_PAGE;
		TEXT_UPDATE_PAGE = EN_INTL_UPDATE_PAGE;

		TEXT_WEATHER = EN_INTL_WEATHER;
		TEXT_TEMPERATURE = EN_INTL_TEMPERATURE;
		TEXT_HUMIDITY = EN_INTL_HUMIDITY;
		TEXT_PRESSURE = EN_INTL_PRESSURE;
		TEXT_DEWPOINT = EN_INTL_DEWPOINT;

		TEXT_AIRPOLLUTION = EN_INTL_AIRPOLLUTION;
		TEXT_SAVED = EN_INTL_SAVED;

		TEXT_POSTCONFIG_INFO = EN_INTL_POSTCONFIG_INFO;
		TEXT_INSTRUCIONSLINK = EN_INTL_INSTRUCIONSLINK;
		TEXT_DEVICENAME = EN_INTL_DEVICENAME;
		TEXT_DEVICENAMEAUTO = EN_INTL_DEVICENAMEAUTO;
		TEXT_SELECTEDLANGUAGE = EN_INTL_SELECTEDLANGUAGE;
		TEXT_TEMPHUMIPRESSSENSOR = EN_INTL_TEMPHUMIPRESSSENSOR;
		TEXT_PMSENSOR = EN_INTL_PMSENSOR;

		TEXT_FREQUENTMEASUREMENTONOFF = EN_INTL_FREQUENTMEASUREMENTONOFF;
		TEXT_FREQUENTMEASUREMENTINFO = EN_INTL_FREQUENTMEASUREMENTINFO;
		TEXT_MEASUREMENTFREQUENCY = EN_INTL_MEASUREMENTFREQUENCY;
		TEXT_AVERAGELASTRESULT = EN_INTL_AVERAGELASTRESULT;
		TEXT_PMMEASUREMENTS = EN_INTL_PMMEASUREMENTS;
		TEXT_SENDINGINTERVAL = EN_INTL_SENDINGINTERVAL;
		TEXT_SECONDS = EN_INTL_SECONDS;
		TEXT_MINUTES = EN_INTL_MINUTES;
		
		TEXT_DEEPSLEEPINFO = EN_INTL_DEEPSLEEPINFO;
		
		TEXT_DISPLAYPM1 = EN_INTL_DISPLAYPM1;
		TEXT_ALTITUDEINFO = EN_INTL_ALTITUDEINFO;

		TEXT_SECURECONFIGUPDATEPAGE = EN_INTL_SECURECONFIGUPDATEPAGE;
		TEXT_SECURELOGIN = EN_INTL_SECURELOGIN;
		TEXT_SECUREPASSWD = EN_INTL_SECUREPASSWD;
		TEXT_SECURELOGOUTINFO = EN_INTL_SECURELOGOUTINFO;

		TEXT_LUFTDATENSENDING = EN_INTL_LUFTDATENSENDING;

		TEXT_AIRMONITORSENDING = EN_INTL_AIRMONITORSENDING;
		TEXT_AIRMONITORCHARTS = EN_INTL_AIRMONITORCHARTS;
		TEXT_AIRMONITORCOORDINATESINFO = EN_INTL_AIRMONITORCOORDINATESINFO;
		TEXT_AIRMONITORLATITUDE = EN_INTL_AIRMONITORLATITUDE;
		TEXT_AIRMONITORLONGITUDE = EN_INTL_AIRMONITORLONGITUDE;

		TEXT_THINGSPEAKSENDING = EN_INTL_THINGSPEAKSENDING;
		TEXT_THINGSPEAKCHARTS = EN_INTL_THINGSPEAKCHARTS;
		TEXT_THINGSPEAKAPIKEY = EN_INTL_THINGSPEAKAPIKEY;
		TEXT_THINGSPEAKCHANNELID = EN_INTL_THINGSPEAKCHANNELID;

		TEXT_INFLUXDBSENDING = EN_INTL_INFLUXDBSENDING;
		TEXT_INFLUXDBSERVER = EN_INTL_INFLUXDBSERVER;
		TEXT_INFLUXDBPORT = EN_INTL_INFLUXDBPORT;
		TEXT_INFLUXDBNAME = EN_INTL_INFLUXDBNAME;
		TEXT_INFLUXDBUSER = EN_INTL_INFLUXDBUSER;
		TEXT_INFLUXDBPASSWD = EN_INTL_INFLUXDBPASSWD;

		TEXT_MQTTSENDING = EN_INTL_MQTTSENDING;
		TEXT_MQTTSERVER = EN_INTL_MQTTSERVER;
		TEXT_MQTTPORT = EN_INTL_MQTTPORT;
		TEXT_MQTTUSER = EN_INTL_MQTTUSER;
		TEXT_MQTTPASSWD = EN_INTL_MQTTPASSWD;

		TEXT_CALIBMETHOD = EN_INTL_CALIBMETHOD;
		TEXT_CALIB1 = EN_INTL_CALIB1;
		TEXT_CALIB2 = EN_INTL_CALIB2;
		TEXT_SOFTWATEVERSION = EN_INTL_SOFTWATEVERSION;

		TEXT_ERASEWIFICONFIG = EN_INTL_ERASEWIFICONFIG;
		TEXT_RESTORESETTINGS = EN_INTL_RESTORESETTINGS;
		TEXT_SAVE = EN_INTL_SAVE;
		TEXT_YES = EN_INTL_YES;
		TEXT_NO = EN_INTL_NO;
		TEXT_WITHOUTSENSOR = EN_INTL_WITHOUTSENSOR;
		TEXT_WITHOUTCALIBRATION = EN_INTL_WITHOUTCALIBRATION;
		TEXT_AUTOMATICCALIBRATION = EN_INTL_AUTOMATICCALIBRATION;

		TEXT_INTL_EN = EN_INTL_INTL_EN;
		TEXT_INTL_PL = EN_INTL_INTL_PL;
		
		TEXT_FWUPDATEAVALIBLE = EN_INTL_FWUPDATEAVALIBLE;
		TEXT_AUTOUPDATEON = EN_INTL_AUTOUPDATEON;
		TEXT_MANUALUPDATEBUTTON = EN_INTL_MANUALUPDATEBUTTON;
		TEXT_FWUPDATEBUTTON = EN_INTL_FWUPDATEBUTTON;
		TEXT_AUTOUPDATEONBUTTON = EN_INTL_AUTOUPDATEONBUTTON;
		TEXT_AUTOUPDATEWARNING = EN_INTL_AUTOUPDATEWARNING;
		TEXT_UPDATEPAGEAUTOUPDATEWARNING = EN_INTL_UPDATEPAGEAUTOUPDATEWARNING;

		TEXT_SELECTUPDATEFILE = EN_INTL_SELECTUPDATEFILE;
		TEXT_SUBMITUPDATE = EN_INTL_SUBMITUPDATE;
		TEXT_CURRENTSOFTVERSION = EN_INTL_CURRENTSOFTVERSION;
		TEXT_SERVERSOFTWAREVERSION = EN_INTL_SERVERSOFTWAREVERSION;
		TEXT_LATESTAVAILABLESOFT = EN_INTL_LATESTAVAILABLESOFT;

		TEXT_HERE = EN_INTL_HERE;
		TEXT_THEFORM = EN_INTL_THEFORM;
	} else if (SELECTED_LANGUAGE == 2) { //polish translation
		Serial.println("Polish Translation!\n");
		TEXT_LANG = PL_INTL_LANG;

		TEXT_INDEX_PAGE = PL_INTL_INDEX_PAGE;
		TEXT_CONFIG_PAGE = PL_INTL_CONFIG_PAGE;
		TEXT_UPDATE_PAGE = PL_INTL_UPDATE_PAGE;

		TEXT_WEATHER = PL_INTL_WEATHER;
		TEXT_TEMPERATURE = PL_INTL_TEMPERATURE;
		TEXT_HUMIDITY = PL_INTL_HUMIDITY;
		TEXT_PRESSURE = PL_INTL_PRESSURE;
		TEXT_DEWPOINT = PL_INTL_DEWPOINT;

		TEXT_AIRPOLLUTION = PL_INTL_AIRPOLLUTION;
		TEXT_SAVED = PL_INTL_SAVED;

		TEXT_POSTCONFIG_INFO = PL_INTL_POSTCONFIG_INFO;
		TEXT_INSTRUCIONSLINK = PL_INTL_INSTRUCIONSLINK;
		TEXT_DEVICENAME = PL_INTL_DEVICENAME;
		TEXT_DEVICENAMEAUTO = PL_INTL_DEVICENAMEAUTO;
		TEXT_SELECTEDLANGUAGE = PL_INTL_SELECTEDLANGUAGE;
		TEXT_TEMPHUMIPRESSSENSOR = PL_INTL_TEMPHUMIPRESSSENSOR;
		TEXT_PMSENSOR = PL_INTL_PMSENSOR;

		TEXT_FREQUENTMEASUREMENTONOFF = PL_INTL_FREQUENTMEASUREMENTONOFF;
		TEXT_FREQUENTMEASUREMENTINFO = PL_INTL_FREQUENTMEASUREMENTINFO;
		TEXT_MEASUREMENTFREQUENCY = PL_INTL_MEASUREMENTFREQUENCY;
		TEXT_AVERAGELASTRESULT = PL_INTL_AVERAGELASTRESULT;
		TEXT_PMMEASUREMENTS = PL_INTL_PMMEASUREMENTS;
		TEXT_SENDINGINTERVAL = PL_INTL_SENDINGINTERVAL;
		TEXT_SECONDS = PL_INTL_SECONDS;
		TEXT_MINUTES = PL_INTL_MINUTES;
		
		TEXT_DEEPSLEEPINFO = PL_INTL_DEEPSLEEPINFO;
		
		TEXT_DISPLAYPM1 = PL_INTL_DISPLAYPM1;
		TEXT_ALTITUDEINFO = PL_INTL_ALTITUDEINFO;

		TEXT_SECURECONFIGUPDATEPAGE = PL_INTL_SECURECONFIGUPDATEPAGE;
		TEXT_SECURELOGIN = PL_INTL_SECURELOGIN;
		TEXT_SECUREPASSWD = PL_INTL_SECUREPASSWD;
		TEXT_SECURELOGOUTINFO = PL_INTL_SECURELOGOUTINFO;

		TEXT_LUFTDATENSENDING = PL_INTL_LUFTDATENSENDING;

		TEXT_AIRMONITORSENDING = PL_INTL_AIRMONITORSENDING;
		TEXT_AIRMONITORCHARTS = PL_INTL_AIRMONITORCHARTS;
		TEXT_AIRMONITORCOORDINATESINFO = PL_INTL_AIRMONITORCOORDINATESINFO;
		TEXT_AIRMONITORLATITUDE = PL_INTL_AIRMONITORLATITUDE;
		TEXT_AIRMONITORLONGITUDE = PL_INTL_AIRMONITORLONGITUDE;

		TEXT_THINGSPEAKSENDING = PL_INTL_THINGSPEAKSENDING;
		TEXT_THINGSPEAKCHARTS = PL_INTL_THINGSPEAKCHARTS;
		TEXT_THINGSPEAKAPIKEY = PL_INTL_THINGSPEAKAPIKEY;
		TEXT_THINGSPEAKCHANNELID = PL_INTL_THINGSPEAKCHANNELID;

		TEXT_INFLUXDBSENDING = PL_INTL_INFLUXDBSENDING;
		TEXT_INFLUXDBSERVER = PL_INTL_INFLUXDBSERVER;
		TEXT_INFLUXDBPORT = PL_INTL_INFLUXDBPORT;
		TEXT_INFLUXDBNAME = PL_INTL_INFLUXDBNAME;
		TEXT_INFLUXDBUSER = PL_INTL_INFLUXDBUSER;
		TEXT_INFLUXDBPASSWD = PL_INTL_INFLUXDBPASSWD;

		TEXT_MQTTSENDING = PL_INTL_MQTTSENDING;
		TEXT_MQTTSERVER = PL_INTL_MQTTSERVER;
		TEXT_MQTTPORT = PL_INTL_MQTTPORT;
		TEXT_MQTTUSER = PL_INTL_MQTTUSER;
		TEXT_MQTTPASSWD = PL_INTL_MQTTPASSWD;

		TEXT_CALIBMETHOD = PL_INTL_CALIBMETHOD;
		TEXT_CALIB1 = PL_INTL_CALIB1;
		TEXT_CALIB2 = PL_INTL_CALIB2;
		TEXT_SOFTWATEVERSION = PL_INTL_SOFTWATEVERSION;

		TEXT_ERASEWIFICONFIG = PL_INTL_ERASEWIFICONFIG;
		TEXT_RESTORESETTINGS = PL_INTL_RESTORESETTINGS;
		TEXT_SAVE = PL_INTL_SAVE;
		TEXT_YES = PL_INTL_YES;
		TEXT_NO = PL_INTL_NO;
		TEXT_WITHOUTSENSOR = PL_INTL_WITHOUTSENSOR;
		TEXT_WITHOUTCALIBRATION = PL_INTL_WITHOUTCALIBRATION;
		TEXT_AUTOMATICCALIBRATION = PL_INTL_AUTOMATICCALIBRATION;

		TEXT_INTL_EN = PL_INTL_INTL_EN;
		TEXT_INTL_PL = PL_INTL_INTL_PL;
		
		TEXT_FWUPDATEAVALIBLE = PL_INTL_FWUPDATEAVALIBLE;
		TEXT_AUTOUPDATEON = PL_INTL_AUTOUPDATEON;
		TEXT_MANUALUPDATEBUTTON = PL_INTL_MANUALUPDATEBUTTON;
		TEXT_FWUPDATEBUTTON = PL_INTL_FWUPDATEBUTTON;
		TEXT_AUTOUPDATEONBUTTON = PL_INTL_AUTOUPDATEONBUTTON;
		TEXT_AUTOUPDATEWARNING = PL_INTL_AUTOUPDATEWARNING;
		TEXT_UPDATEPAGEAUTOUPDATEWARNING = PL_INTL_UPDATEPAGEAUTOUPDATEWARNING;
		
		TEXT_SELECTUPDATEFILE = PL_INTL_SELECTUPDATEFILE;
		TEXT_SUBMITUPDATE = PL_INTL_SUBMITUPDATE;
		TEXT_CURRENTSOFTVERSION = PL_INTL_CURRENTSOFTVERSION;
		TEXT_SERVERSOFTWAREVERSION = PL_INTL_SERVERSOFTWAREVERSION;
		TEXT_LATESTAVAILABLESOFT = PL_INTL_LATESTAVAILABLESOFT;

		TEXT_HERE = PL_INTL_HERE;
		TEXT_THEFORM = PL_INTL_THEFORM;
	} else { //others future translations
		Serial.println("Other Translation!\n");
		
	}
}